In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

In [6]:
v1 = np.array([1,2,3,4,5])

In [7]:
v2 = np.array([10,20,30,40,50])

In [13]:
mask = v2 > 20
mask

array([False, False,  True,  True,  True])

In [14]:
v2[mask]

array([30, 40, 50])

In [15]:
v2[v2>20]

array([30, 40, 50])

In [18]:
v2[0] =100
v2

array([100,  20,  30,  40,  50])

In [19]:
v1[:2]

array([1, 2])